/**
 * Daily standup summary page.
 *
 * Combines a hero band, four color-toned sections (Completed Today, In
 * Progress, Paused, Interrupted Today), and a plain-text summary block the
 * user can copy into Slack or email.
 */
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'
import Icon from '../components/Icons'
import { PageEyebrow } from '../components/Atoms'

const SECTIONS = [
  { key: 'completed',   label: 'Completed',         tone: 'done' },
  { key: 'in_progress', label: 'In Progress',       tone: 'progress' },
  { key: 'paused',      label: 'Paused',            tone: 'paused' },
  { key: 'interrupted', label: 'Interrupted',       tone: 'alert' },
]

/** Local ISO date (YYYY-MM-DD) without UTC drift. */
function todayLocal() {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

/** Shift an ISO date by N days. */
function shiftIso(iso, days) {
  const d = new Date(`${iso}T00:00:00`)
  d.setDate(d.getDate() + days)
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

export default function StandupPage() {
  const [date, setDate] = useState(todayLocal())
  const [data, setData] = useState(null)
  const [copied, setCopied] = useState(false)
  const summaryRef = useRef(null)
  const navigate = useNavigate()

  const isToday = date === todayLocal()

  // Re-fetch whenever the selected date changes. We keep the old data on
  // screen while the new payload loads so day-to-day navigation feels
  // instant; the spinner only appears on the very first load.
  useEffect(() => {
    let cancelled = false
    api.getStandup(date).then(d => { if (!cancelled) setData(d) })
    return () => { cancelled = true }
  }, [date])

  // Long-form heading like "Monday, May 25" using the today date the backend returned.
  const todayStr = data?.today
  const headingDate = useMemo(() => {
    if (!todayStr) return ''
    const d = new Date(`${todayStr}T00:00:00`)
    return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })
  }, [todayStr])

  const total = useMemo(() => {
    if (!data) return 0
    return SECTIONS.reduce((sum, s) => sum + (data[s.key]?.length ?? 0), 0)
  }, [data])
  // Conic-gradient progress ring: clamp so the arc is always visible.
  const ringDeg = Math.min(340, Math.max(40, total === 0 ? 40 : (total / Math.max(total, 4)) * 360))

  const summaryText = useMemo(() => {
    if (!data) return ''
    const lines = [`DevOrbit · Daily Standup — ${data.today}`, '='.repeat(40), '']
    SECTIONS.forEach(s => {
      const items = data[s.key] ?? []
      lines.push(`${s.label.toUpperCase()} (${items.length})`)
      if (items.length === 0) lines.push('  · None')
      else items.forEach(t => lines.push(`  · ${t.title} [${t.priority}]`))
      lines.push('')
    })
    lines.push('— Generated by DevOrbit')
    return lines.join('\n')
  }, [data])

  // Auto-grow the textarea to fit every line of the generated summary.
  useEffect(() => {
    const el = summaryRef.current
    if (!el) return
    el.style.height = 'auto'
    el.style.height = `${el.scrollHeight}px`
  }, [summaryText])

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!data) return <div className="loading"><div className="spinner" /></div>

  return (
    <>
      <PageEyebrow kicker="Daily Report" title="Standup Summary" />

      <div className="standup__hero">
        <div>
          <div className="panel__label">{isToday ? 'Today' : 'Selected Day'}</div>
          <h1>{headingDate}</h1>
          <p>{total} tracked items across {SECTIONS.length} groups</p>
          <div className="standup__date-row">
            <button
              type="button"
              className="standup__date-nav"
              onClick={() => setDate(shiftIso(date, -1))}
              aria-label="Previous day"
            >
              <Icon name="chev" size={12} style={{ transform: 'rotate(90deg)' }} />
            </button>
            <input
              type="date"
              className="standup__date-input"
              value={date}
              max={todayLocal()}
              onChange={e => e.target.value && setDate(e.target.value)}
              aria-label="Standup date"
            />
            <button
              type="button"
              className="standup__date-nav"
              onClick={() => setDate(shiftIso(date, 1))}
              disabled={isToday}
              aria-label="Next day"
            >
              <Icon name="chev" size={12} style={{ transform: 'rotate(-90deg)' }} />
            </button>
            {!isToday && (
              <button
                type="button"
                className="standup__date-today"
                onClick={() => setDate(todayLocal())}
              >
                Today
              </button>
            )}
          </div>
        </div>
        <div className="standup__ring" style={{ '--ring-deg': `${ringDeg}deg` }}>
          <div className="standup__ring-inner">
            <div className="standup__ring-num">{total}</div>
            <div className="standup__ring-lbl">Items</div>
          </div>
        </div>
      </div>

      <div className="standup__grid">
        {SECTIONS.map(s => {
          const items = data?.[s.key] ?? []
          return (
            <div key={s.key} className={`standup__sect tone-${s.tone}`}>
              <div className="standup__sect-head">
                <span className="standup__sect-pip" />
                <span>{s.label}</span>
                <span className="standup__sect-count">{items.length}</span>
              </div>
              {items.length === 0 ? (
                <div className="standup__empty">None</div>
              ) : items.map(t => (
                <div
                  key={t.id}
                  className="standup__item"
                  onClick={() => navigate(`/tasks/${t.id}`)}
                  role="button"
                  tabIndex={0}
                  onKeyDown={e => { if (e.key === 'Enter') navigate(`/tasks/${t.id}`) }}
                  style={{ cursor: 'pointer' }}
                >
                  <span className={`dot p-${t.priority}`} style={{ marginTop: 5 }} />
                  <div>
                    <div className="standup__item-title">{t.title}</div>
                    <span className={`badge p-${t.priority}`}>{t.priority}</span>
                  </div>
                </div>
              ))}
            </div>
          )
        })}
      </div>

      <div className="standup__copy">
        <div className="standup__copy-head">
          <span>Plain-text summary</span>
          <button type="button" className="standup__copy-btn" onClick={handleCopy}>
            <Icon name={copied ? 'check' : 'copy'} size={11} />
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
        <textarea
          ref={summaryRef}
          className="standup__textarea"
          value={summaryText}
          readOnly
        />
      </div>
    </>
  )
}
