/**
 * Daily standup summary page.
 *
 * Presents the backend standup aggregation visually and generates a plain-text
 * summary suitable for chat, email, or meeting notes.
 */
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import Icon from '../components/Icons'

const SECTIONS = [
  { key: 'completed', label: 'Completed Today', tone: 'done' },
  { key: 'in_progress', label: 'In Progress', tone: 'progress' },
  { key: 'paused', label: 'Paused', tone: 'paused' },
  { key: 'interrupted', label: 'Interrupted Today', tone: 'alert' },
]

/** Render the daily standup dashboard and copyable report. */
export default function StandupPage() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)

  // Fetch the standup payload once on page load.
  useEffect(() => {
    let cancelled = false
    api.getStandup()
      .then(d => {
        if (!cancelled) setData(d)
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => { cancelled = true }
  }, [])

  /** Convert grouped standup data into a stable plain-text report. */
  const buildText = () => {
    if (!data) return ''
    const lines = [`DevOrbit - Daily Standup Summary (${data.today})`, '='.repeat(45)]
    SECTIONS.forEach(s => {
      const items = data[s.key] ?? []
      lines.push(`\n${s.label.toUpperCase()} (${items.length})`)
      items.forEach(t => lines.push(`  - ${t.title} [${t.priority}]`))
      if (!items.length) lines.push('  - None')
    })
    lines.push('\n' + '='.repeat(45))
    lines.push('Generated by DevOrbit')
    return lines.join('\n')
  }

  /** Copy the generated standup text to the clipboard and show brief feedback. */
  const handleCopy = () => {
    navigator.clipboard.writeText(buildText())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (loading) return <div className="loading-page"><div className="spinner" /></div>

  return (
    <>
      <div className="main-topbar">
        <div className="topbar-breadcrumb">
          <Link to="/">Dashboard</Link>
          <span className="crumb-muted">Standup Summary</span>
        </div>
        <div className="topbar-right">
          <button type="button" className="btn-ghost" onClick={handleCopy}>
            <Icon name={copied ? 'check' : 'copy'} size={15} />
            {copied ? 'Copied' : 'Copy'}
          </button>
          <Link to="/tasks/new" className="btn-primary"><Icon name="plus" size={15} />New Task</Link>
        </div>
      </div>

      <div className="main-scroll">
        <div>
          <div className="standup-hero">
            <div>
              <div className="panel-label">Daily Report</div>
              <h1>Standup Summary</h1>
              <p>{data?.today}</p>
            </div>
            <div className="standup-total">
              <span>{SECTIONS.reduce((sum, s) => sum + (data?.[s.key]?.length ?? 0), 0)}</span>
              <strong>tracked items</strong>
            </div>
          </div>

          <div className="standup-grid">
            {SECTIONS.map(s => {
              const items = data?.[s.key] ?? []
              return (
                <div
                  key={s.key}
                  className={`standup-section tone-${s.tone}`}
                >
                  <div className="standup-section-head">
                    <span className="section-pip" />
                    <span>{s.label}</span>
                    <span className="standup-count">{items.length}</span>
                  </div>
                  {items.length > 0 ? items.map(t => (
                    <Link key={t.id} to={`/tasks/${t.id}`} className="standup-item">
                      <span className={`priority-dot p-${t.priority}`} />
                      <div>
                        <div>{t.title}</div>
                        <span className={`badge p-${t.priority}`}>{t.priority}</span>
                      </div>
                    </Link>
                  )) : (
                    <p className="standup-empty">None</p>
                  )}
                </div>
              )
            })}
          </div>

          <div className="standup-text-block">
            <div className="standup-text-top">Plain-text summary</div>
            <textarea className="standup-textarea" readOnly value={buildText()} />
          </div>
        </div>
      </div>
    </>
  )
}
